name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
        id: go

      - name: Test
        run: go test -v .
